CREATE TABLE merchants (
    id              bigint                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255)            NOT NULL,
    email           varchar(255)            DEFAULT NULL,
    webhook         varchar(255)            NOT NULL,
    tax_number      varchar(9)              NOT NULL,
    login           varchar(255)            NOT NULL,
    password        varchar(80)             NOT NULL,
    created_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_merchants_tax_number UNIQUE (tax_number),
    CONSTRAINT uk_merchants_login UNIQUE (login)
);

